### ISSUE TITLE
cmake: if the BLAS provider is OpenBLAS, ensure we're not linking against a pthreaded version

### ISSUE THREAD

**Issue by dev-zero** [cp2k/dbcsr#295]
pthreaded OpenBLAS breaks at runtime (in a verbose and obvious way). If we detect that the BLAS provider is OpenBLAS we should try `find_package(OpenBLAS ... COMPONENTS openmp)` to override by an OpenMP-parallel or single-threaded version of OpenBLAS if possible.

**Comment by dev-zero** [comment]
Does it make sense for DBCSR to use a (OpenMP) threaded BLAS at all or should we always be using a single-threaded BLAS since we do threading ourselves?

**Comment by dev-zero** [comment]
The thing to use an OpenMP-threaded OpenBLAS was always done under the assumption that if we do nested threading (calling a BLAS op from a OpenMP thread it will run single-threaded) it will be of almost no cost. Experience in CP2K although has shown that at least with GNU Fortran the cost can be quiet high: https://github.com/cp2k/cp2k/commit/63f2e15396cd4d5323c594035dca6ba31437099f

**Comment by alazzaro** [comment]
This is a good question and it is relevant for CP2K too.
The current policy in CP2K (see https://github.com/cp2k/cp2k/blob/master/INSTALL.md#2d-blas-and-lapack-required-base-functionality ) is not use a threaded BLAS. The reason is the nested parallelism. In principle, we can set `OMP_NESTED=false` and the problem should be fixed.
For some BLAS implementations, i.e. Cray libsci, this is automatic (the library recognizes if you are in a parallel region already or not, and it will be avoid nested). It seems that Intel MKL does too (see https://software.intel.com/en-us/mkl-macos-developer-guide-calling-intel-mkl-functions-from-multi-threaded-applications).
