### ISSUE TITLE
Include loggers and timers creation in dbcsr_init_lib/finalize

### ISSUE THREAD

**Issue by alazzaro** [cp2k/dbcsr#32]

**Comment by dithillobothrium** [comment]
I wanted to do that but there were some difficulties. Temporarily I created separate functions 
https://github.com/dithillobothrium/dbcsr-1/blob/1c36e71ea275ffb767998ef51dee11634e79de3b/src/dbcsr_api.F#L466

**Comment by dithillobothrium** [comment]
I removed extras/ to core/ and added creation printing and destroying timers in dbcsr_lib. But now it is impossible to call these function from dbcsr_init_lib() because to create timers one needs a grid and communicator. One of the ways could be to create wrapper function "dbcsr_init(finlaize)_lib" (may bi in dbcsr_api) which takes communicator and grid as a parameter to create timers.
