### ISSUE TITLE
Temporary arrays checks

### ISSUE THREAD

**Issue by alazzaro** [cp2k/dbcsr#325]
Keeping as a reference

https://github.com/cp2k/dbcsr/pull/322#issuecomment-603811467

**Comment by alazzaro** [comment]
@hfp The flags are reporting in https://github.com/cp2k/dbcsr/pull/322#issuecomment-603811467 are the same we use in our DBG tests of CP2K?
Then, why we don't get a warning for temporary array creation?

**Comment by hfp** [comment]
No idea, I always had these messages and noticed nobody else...

I used GCC 8.4, but that is not the key. I will keep a side task to find out.

**Comment by alazzaro** [comment]
Related to the temporary array, we are currently using the flag `-fcheck=all` in the CI. However, it turns out that the temporary array is a warning, which we don't check.
I've tried to add `-Werror` to promote the warning to an error, but it doesn't work with the `-fcheck`. The only solution is to use `-Werror=array-temporaries`, however now I get a lot of errors in the mpiwrap module, due to missing `CONTIGUOUS` keyword.

**Comment by hfp** [comment]
I added some CONTIGUOUS keywords in previous PRs, but I cannot remember why I did not cover all cases. I mean worst case (wrapper, etc.), it might be ok to even put my [anti-pattern](https://github.com/cp2k/cp2k/pull/861#issuecomment-613101315) to get some 1-dimensional arrays.

**Comment by oschuett** [comment]
Since Fortran pointers are generally not contiguous and mpiwrap has many call sites, that [anti-pattern](https://github.com/cp2k/cp2k/pull/861#issuecomment-613101315) would most probably not work. Furthermore, the non-contiguousness is actually a desirable feature which allows for powerful array expressions.

The root problem seems to be that we're passing Fortran 90 pointers to Fortran 77 MPI bindings.
Isn't there anything in the MPI 3 standard that would allow us to tell the MPI library the actual layout of our data?

**Comment by alazzaro** [comment]
From what I see, most of the temporaries are not critical at all (orders, grids...).
Then, as we discussed in this issue https://github.com/cp2k/dbcsr/issues/253, the plan (in the very long run) is to migrate to a C interface, so that we drop the F77 and multi-compiler problem...

**Comment by oschuett** [comment]
So, to summaries the temporary copies happen in two cases:
 1. When they are unavoidable due to some complex array expression.
 2. When we call into F77 code, ie. MPI, BLAS, etc.

Since, we want to keep 1. and won't fix 2. anytime soon, I'd suggest we disable the warnings for now.

**Comment by alazzaro** [comment]
Disable the warnings in CP2K is fine (you did already), however I would keep it for DBCSR just to "annoy" people when the compile in Debug mode (via cmake).
Then, I went a bit more extreme and added the flag `-Warray-temporaries`, so that I get a message when a temporary is created at compiling time. It turns out that there are 2288 temporaries. Basically, GCC is generating a temporary whenever we use (abuse?) a pointer. Most of them can be avoided by adding the keyword `CONTIGUOUS` (we need pointers in some cases). Therefore, I opened PR #341 and start to add CONTIGUOUS to some pointers (incremental). It turns out that:

1. I've started with the data (i.e. no integers). It turns out that FORTRAN does padding for the 2D data arrays, so I cannot use CONTIGUOUS there (we do reshape between 1D and 2D). The good point is that 2D data are used only internally in the tensor part (likely we can remove them in the future, as confirmed by @pseewald ), so 2D arrays are not critical

2. Moving to indices, this part is a bit more tricky. First of all, all compilers are doing in a different way: Intel is fine, GNU requires special attention, CCE doesn't work (I did workaround to get it to compile the code, but it produces wrong results). Then, since I don't want to change the API, I did some temporaries by hand, so CP2K is happy too. 

Continuing to avoid temporaries...

**Comment by oschuett** [comment]
Unfortunately, `-Warray-temporaries` has many false positives. Basically, it warns whenever the frontend inserts a code path that **might** create a temporary. Often the code is later optimized away or never executed because at runtime the pointers are contiguous. 

See also [this gcc bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=48655) and its duplicates.

Nevertheless, `-Warray-temporaries` is the only way to eliminate all temporaries for sure and it would be cool if you managed to pull that off for DBCSR.

**Comment by alazzaro** [comment]
closed via #341
