### ISSUE TITLE
Switch build_utils and fypp to Python3

### ISSUE THREAD

**Issue by oschuett** [cp2k/dbcsr#386]
Most distributions are now missing the `python` binary by default. Hence, the [build_utils](https://github.com/cp2k/dbcsr/blob/develop/.cp2k/) and [fypp](https://github.com/cp2k/dbcsr/tree/develop/tools/build_utils) should use `python3` instead.

Alternatively, instead of grandfathering the old Makefile we could move the DBCSR build into the toolchain, ie. https://github.com/cp2k/cp2k/issues/351.

**Comment by dev-zero** [comment]
Thanks for the report, fixed in 97086fa19d40784b48a7580377b26bfd48ac552d and a37026c3955d4447000f87791da7f78d20107423.

No, people struggle enough already with the usual toolchain changes. As long as there is no automated toolchain-rebuild (as can be provided with the Spack-based toolchain) and/or a stable enough API from DBCSR I am not going to sacrifice their time without providing any benefit.

**Comment by oschuett** [comment]
Thanks for the changes. Hopefully, the DBCSR API stabilizes in the near future.
