### ISSUE TITLE
Recipe for using DBCSR/develop in CP2K

### ISSUE THREAD

**Issue by hfp** [cp2k/dbcsr#86]
It would be handy to have a recipe for using DBCSR/develop in CP2K. The recipe is not meant to touch open questions (Git-submodules, etc.), but rather meant to have at least a list of (manual) steps to follow. It may also serve as a work-item to initially harmonize both sources (CP2K build system to account for renamed files, etc.).

**Comment by alazzaro** [comment]
@dev-zero is working on that.
This is the receipt (not sure if it still works), which are based on my CP2K-svn repo:

https://github.com/alazzaro/cp2k/tree/master/cp2k

-) remove the directories src/dbcsr and src/dbcsr_tensor
-) remove the directories tools/build_libsmm and tools/dbcsr_test
-) Update of the corresponding PACKAGEs file: src/arnoldi/PACKAGE, src/dbcsrx/PACKAGE, src/emd/PACKAGE, src/motion/PACKAGE, src/PACKAGE, src/start/PACKAGE
-) Update of src/f77_interface.F to have DBCSR timers add loggers hooks in CP2K
-) Update of the Makefile
-) Include the exts directory (makefile, dbcsr as submodule/copy)

The CP2K calls the DBCSR make (see exts/Makefile.inc). As a configuration for the DBCSR compilation it uses the same CP2K arch file (they are compatible). The obj and libraries will be copied under the corresponding CP2K directories. *Note that any change in DBCSR library will force a full compilation of CP2K*. I don't think this is a problem because no so many people are developing DBCSR.

**Comment by hfp** [comment]
Thank you, Alfio for sharing the steps!

**Comment by hfp** [comment]
https://github.com/cp2k/cp2k/issues/52

**Comment by pseewald** [comment]
I'm just about to create a pull request for CP2K that replaces CP2K-internal DBCSR with standalone DBCSR based on Alfio's fork. Then we have a CP2K branch that works with standalone DBCSR and the pull request can be updated following our ongoing discussions (git-submodules etc).
